### ISSUE TITLE
Element misalignment on landing page

### ISSUE THREAD

**Issue by mendozagioo** [bandohq/react-bando#168]
There are a misalignment in the second section (visible) of the landing page.

I can see the first and second section correspond to a similar alignment according to the rest of elements.
I think the second section expands too much and looks bad visually since it expands the width of the video

![Screenshot 2024-08-05 at 12 29 17 p m](https://github.com/user-attachments/assets/4b99d09f-73fa-4632-9f1c-57316e9f8415)

![Screenshot 2024-08-05 at 12 36 38 p m](https://github.com/user-attachments/assets/17ebeeb3-91ac-4de5-bddd-75d4f36a4b35)

![Screenshot 2024-08-05 at 12 38 28 p m](https://github.com/user-attachments/assets/fc95fb5b-37f2-4b43-8093-821ae2c1bcce)

In my POV there are another visual errors on the same landing page but probably is for my lack of context.

**Comment by luisgj** [comment]
@mendozagioo Thanks for bringing this into a formal issue :D. 
Indeed the alignment of the second section must be aligned.
